### ISSUE TITLE
Add ability to validate non-default config file

### ISSUE THREAD

**Issue by Ichimonji10** [Ichimonji10/killjoy#5]
Expand the `killjoy settings validate` subcommand. It currently checks the validity of whatever file killjoy would use when next starting. In other words, it typically checks the validity of `~/.config/killjoy/settings.json`. It should be possible to validate a non-default configuration file, with a command like `killjoy settings validate path/to/settings.json`.

This issue is derived from #4.

**Comment by cshlatz** [comment]
Even if you choose not to use this (and I think you'll choose not to), I think it's worth a discussion.

clap has the ability to load command line arguments from YAML files, which is discussed on the main crate page for clap (https://docs.rs/clap/2.33.0/clap/ ctrl+f for "third method"). This would help separate data from the code - nobody likes having to rebuild a project just to change some strings around. It would also likely be much easier to manage when this chunk inevitably grows.

The bad: I'm not sure how we'd handle the terminal wrap prettifying. This is also a feature that's not in clap by default and it has to be compiled in. This would make killjoy have a larger footprint when one of the goals seems to be to keep it low.

All that being said, I'm not sure the paragraphs currently in cli.rs are needed for a command line help message when properly documented arguments and flags can get the point across with a sentence.

**Comment by Ichimonji10** [comment]
There's a couple reasons I'm using the current method of generating a CLI interface:

1. It has more features and is faster than the second method. I suspect it's faster than the third method too, as lexing and parsing is generally an expensive operation.
2. It's available by default, as opposed to the third method (YAML).
3. It can be validated at compile time, as opposed to the second and third methods.

These aren't set-in-stone reasons to use the first technique for creating the CLI. But they nudge me in that direction.

---

> [Using YAML files] would help separate data from the code - nobody likes having to rebuild a project just to change some strings around.

Interesting claim. The clap docs say the same thing:

> This third method shows how you can use a YAML file to build your CLI and keep your Rust source tidy or support multiple localized translations by having different YAML files for each localization.

But I don't see how that claim is true.

If the goal is to separate data (i.e. human-readable help messages) from code (the structure and behavior of the CLI), using YAML seems like a poor choice.  Imagine if you wanted to support English and Spanish. You might write two YAML files, where the first has English strings:

```yaml
name: myapp
version: "1.0"
author: Kevin K. <kbknapp@gmail.com>
about: Does awesome things
args:
    - config:
        short: c
        long: config
        value_name: FILE
        help: Sets a custom config file
        takes_value: true
    - INPUT:
        help: Sets the input file to use
        required: true
        index: 1
    - verbose:
        short: v
        multiple: true
        help: Sets the level of verbosity
```

…and the second uses Spanish strings:

```yaml
name: myapp
version: "1.0"
author: Kevin K. <kbknapp@gmail.com>
about: Fait des choses géniales
args:
    - config:
        short: c
        long: config
        value_name: FILE
        help: Définit un fichier de configuration personnalisé
        takes_value: true
    - INPUT:
        help: Définit le fichier d'entrée à utiliser
        required: true
        index: 1
    - verbose:
        short: v
        multiple: true
        help: Définit le niveau de verbosité
```

By doing this, the structure of the CLI interface is being duplicated. If one wishes to edit the CLI in any way, then two YAML files must be edited and kept in sync. Imagine if one wanted to support five different languages, or if one had a more complex CLI. This is a recipe for bugs! I don't see how it separates code from data.

A better way to support multiple languages might be to write the CLI interface using one of the other techniques, and then fill in text like this:

```rust
fn get_cli_parser() -> App {
    App::new("My Super Program")
        .version("1.0")
        .author("Kevin K. <kbknapp@gmail.com>")
        .about(get_msg("about"))
        .arg(Arg::with_name("config")
            .short("c")
            .long("config")
            .value_name("FILE")
            .help(get_msg("config"))
            .takes_value(true))
        .arg(Arg::with_name("INPUT")
            .help(get_msg("INPUT"))
            .required(true)
            .index(1))
        .arg(Arg::with_name("v")
            .short("v")
            .multiple(true)
            .help(get_msg("v")))
}

// Get the help message with the given ID for the current locale. If help
// strings don't exist for the current locale, get help strings for the en_US
// locale.  Return an error if the given ID doesn't have a corresponding
// message.
fn get_msg(msg_id: &str) -> Result<String, …> { … }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn get_cli_parser_en_us() {
        // Set locale somehow.
        get_cli_parser();
    }

    #[test]
    fn get_cli_parser_es_es() {
        // Set locale somehow.
        get_cli_parser();
    }
}
```

---

> This would make killjoy have a larger footprint when one of the goals seems to be to keep that footprint as small as possible.

Yes, I want to have a small footprint. I'll be doing some profiling down the road to see what contributes to its footprint. Perhaps I could use feature flags to optionally enable niceties like text wrapping?
